### ISSUE TITLE
oldState argument for subscribed functions. 

### ISSUE THREAD

**Issue by eldonwilliams** [orYoffe/jstates#12]
I would like to see a feature added to pass the old state as an argument when firing the subscribed events. I have created an implementation _(that is honestly pretty bad, but works)_ however, I think a better one could be made. Consider merging mine if you think it is sufficient or adding this yourself.

Thank you!

**Comment by eldonwilliams** [comment]
I planned on attaching the PR for this feature through the linked pull requests feature, however, I think it is disabled for me to edit. I'll link to it for ease of access. https://github.com/orYoffe/jstates/pull/13

**Comment by orYoffe** [comment]
check the Readme plz
