### ISSUE TITLE
 is the library still valid?

### ISSUE THREAD

**Issue by vizardkill** [orYoffe/jstates#16]
It is a very practical library to handle javascript files with states, but I see that it has been abandoned?

**Comment by giliyoffe** [comment]
בוקר טוב
בטח עוד לא ראית את זה.
סתם מעניין למה הוא/יא כתב את זה.
בטח רוצים להשתמש וחושבים אם תהיה תמיכה.

**Comment by orYoffe** [comment]
check the Readme plz
